language: php

env:
 - PECL_HTTP_VERSION=1.7.6
 - PECL_HTTP_VERSION=2.4.3

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
 - printf "\n\n\n" | pecl install -f pecl_http-$PECL_HTTP_VERSION

script:
 - phpunit --configuration test/phpunit.xml


matrix:
  fast_finish: true
